### ISSUE TITLE
Get 100% for golint

### ISSUE THREAD

**Issue by Bunchhieng** [Bunchhieng/hnreader#28]
Here is the report: https://goreportcard.com/report/github.com/Bunchhieng/hnreader

**Comment by haritsfahreza** [comment]
Hi @Bunchhieng!

I would like to solve this issue 💪 Stay tuned!

**Comment by gabolaev** [comment]
But... it's already ok
https://goreportcard.com/report/github.com/Bunchhieng/hnreader#golint
![image](https://user-images.githubusercontent.com/10693243/46611890-c388aa00-cb17-11e8-8cf2-53354f67a188.png)

**Comment by Bunchhieng** [comment]
ah okay. I checked this morning and it was 50%. good catch. Right now the `misspell` is at 50%.

**Comment by haritsfahreza** [comment]
Done on misspell please take a look @Bunchhieng 😄 🙏

**Comment by Bunchhieng** [comment]
@haritsfahreza @gabolaev Thanks. closing the issue.
